name: app_build
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  flutter_form_builder: ^9.5.0
  fluttertoast: ^8.2.10
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS --------------#

  assets:
    - assets/images/contents/
    - assets/images/logos/
    - assets/sound/

  #--------------- LOCAL ASSETS END ----------#