// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZcB46jhg14XrsldsdklHYgW6TnjIQhrM',
    appId: '1:778693416791:web:0ac50d5b76d49f273b1012',
    messagingSenderId: '778693416791',
    projectId: 'itti-notification',
    authDomain: 'itti-notification.firebaseapp.com',
    storageBucket: 'itti-notification.appspot.com',
    measurementId: 'G-T28CYZMDDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqKmzVvJlky9t12pnDr76zWm1K7dzjTY',
    appId: '1:778693416791:android:50c4a47007043e3a3b1012',
    messagingSenderId: '778693416791',
    projectId: 'itti-notification',
    storageBucket: 'itti-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBK1lnhWlX4fLMkjmpHzZLjQzEY0bnqZ8',
    appId: '1:778693416791:ios:cb7755db2e1914443b1012',
    messagingSenderId: '778693416791',
    projectId: 'itti-notification',
    storageBucket: 'itti-notification.appspot.com',
    iosBundleId: 'itti.now.approve',
  );

}